version: '2'
services:
  schedulerdb:
    scale: 1
    start_on_create: true
  zeppelin:
    scale: 1
    start_on_create: true
  configdb:
    scale: 1
    start_on_create: true
  configinit:
    scale: 1
    start_on_create: true
  iotbrokerservice:
    scale: 1
    start_on_create: true
  apimanagerservice:
    scale: 1
    start_on_create: true
  loadbalancerservice:
    scale: 1
    start_on_create: true
  quasar:
    scale: 1
    start_on_create: true
  monitoringuiservice:
    scale: 1
    start_on_create: true
  dashboardengineservice:
    scale: 1
    start_on_create: true
  routerservice:
    scale: 1
    start_on_create: true
  cacheservice:
    scale: 1
    start_on_create: true
  controlpanelservice:
    scale: 1
    start_on_create: true
  realtimedb:
    scale: 1
    start_on_create: true
